# 1-p scoring function configuration for multiple datasets
inherit: base_config.yaml

# Device configuration
device: 1  # GPU=0/1 and CPU=-1

# Directory paths
data_dir: data  # Directory where datasets are stored
base_dir: .     # Base directory for relative paths

# Dataset configurations
dataset:
  name: cifar10  # Default dataset
  num_classes: 10
  input_size: [32, 32]
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.2010]

# CIFAR-100 specific configuration
cifar100:
  num_classes: 100
  input_size: [32, 32]
  mean: [0.5071, 0.4865, 0.4409]
  std: [0.2673, 0.2564, 0.2762]

# ImageNet specific configuration
imagenet:
  num_classes: 1000
  input_size: [224, 224]
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  data_dir: data/imagenet  # Specific path for ImageNet dataset

# Model configurations
model:
  architecture: resnet18  # Default for CIFAR-10
  pretrained_path: models/resnet18_cifar10_best.pth
  img_size: 32  # Default for CIFAR datasets
  drop_path_rate: 0.0  # Default value
  drop_rate: 0.0  # Default value

# Model paths for different datasets
model_paths:
  cifar10: models/resnet18_cifar10_best.pth
  cifar100: models/vit_cifar100.pth  # Updated to match the path in cifar100.yaml
  imagenet: models/vit_imagenet.pth  # Updated to match the path in imagenet.yaml

# Model-specific configurations
model_configs:
  cifar10: {}
  cifar100:
    architecture: vit_base_patch16_224_in21k
    img_size: 96
    drop_path_rate: 0.1
    drop_rate: 0.1
  imagenet:
    architecture: vit_base_patch16_224
    img_size: 224
    drop_path_rate: 0.1
    drop_rate: 0.1

# Paths
plot_dir: plots/1-p
log_dir: logs/1-p

# Batch size for evaluation
batch_size: 128

# Target coverage
target_coverage: 0.9

# No need for training parameters since 1-p doesn't require training 