# CIFAR-10 specific configuration
inherit: base_config.yaml

dataset:
  name: cifar10
  num_classes: 10
  input_size: [32, 32]
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.2010]

model:
  architecture: resnet18
  pretrained_path: models/resnet18_cifar10_best.pth 

# Training parameters
num_epochs: 50
batch_size: 128
learning_rate: 0.001
lambda1: 1.0  # Coverage loss weight
lambda2: 1.0  # Set size loss weight
target_coverage: 0.9

# Model architecture
scoring_function:
  hidden_dims: [64, 32]
  dropout: 0.2
  l2_lambda: 0.1

# Training constraints
tau:
  min: 0.1
  max: 0.9
  window_size: 5

# Set size constraints
set_size:
  target: 1.2
  max: 3.0
  margin: 0.2 