# CIFAR-100 specific configuration
inherit: base_config.yaml

# Device configuration
device: 0

dataset:
  name: cifar100
  num_classes: 100
  input_size: [32, 32]
  mean: [0.5071, 0.4867, 0.4408]
  std: [0.2675, 0.2565, 0.2761]

model:
  architecture: vit_base_patch16_224_in21k
  pretrained_path: models/vit_cifar100.pth
  img_size: 96
  drop_path_rate: 0.1
  drop_rate: 0.1

# Paths
plot_dir: plots/cifar100
log_dir: logs/cifar100

# Training parameters
num_epochs: 50
batch_size: 128
target_coverage: 0.9

# Training configuration
training:
  grad_clip:
    enabled: true
    max_norm: 0.5
  loss_weights:
    coverage: 2.0  # lambda1
    size: 1.0      # lambda2
    margin: 2    # margin loss weight

# Optimizer configuration
optimizer:
  name: 'AdamW'
  params:
    lr: 0.001
    weight_decay: 0.01
  scheduler:
    name: 'OneCycleLR'
    params:
      max_lr: 0.001
      pct_start: 0.2
      div_factor: 20
      final_div_factor: 100
      anneal_strategy: 'cos'

# Model architecture
scoring_function:
  hidden_dims: [64, 32]
  dropout: 0.2
  l2_lambda: 0.1
  activation:
    name: 'LeakyReLU'
    params:
      negative_slope: 0.1
  final_activation:
    name: 'Softplus'
    params:
      beta: 10

# Training constraints
tau:
  min: 0.1
  max: 0.9
  window_size: 5

# Set size constraints
set_size:
  target: 1
  max: 3
  margin: 5