# CIFAR-100 specific configuration
inherit: base_config.yaml

# Device configuration
device: 1

# Caching configuration
cache:
  enabled: true
  dir: cache  # Will be created under base_dir
  compression: false  # Whether to use compression for cached files

dataset:
  name: cifar100
  num_classes: 100
  input_size: [32, 32]
  mean: [0.5071, 0.4867, 0.4408]
  std: [0.2675, 0.2565, 0.2761]

model:
  architecture: vit_base_patch16_224_in21k
  pretrained_path: models/vit_cifar100.pth
  img_size: 96
  drop_path_rate: 0.1
  drop_rate: 0.1

# Paths
plot_dir: plots/cifar100
log_dir: logs/cifar100

# Training parameters
num_epochs: 50
batch_size: 128
target_coverage: 0.9

# Training configuration
training:
  grad_clip:
    enabled: true
    max_norm: 0.5
  loss_weights:
    coverage: 4.0  # lambda1 - increased from 2.0 for better coverage control
    size: 1.5      # lambda2 - increased from 1.0 for better set size control
    margin: 0.2    # margin loss weight - reduced from 2 to avoid dominating training

# Optimizer configuration
optimizer:
  name: 'AdamW'
  params:
    lr: 0.0002  # Reduced from 0.001 for better stability
    weight_decay: 0.01
  scheduler:
    name: 'OneCycleLR'
    params:
      max_lr: 0.0002  # Reduced from 0.001 to match base lr
      pct_start: 0.2
      div_factor: 20
      final_div_factor: 100
      anneal_strategy: 'cos'

# Model architecture
scoring_function:
  hidden_dims: [128, 64]  # Increased from [64, 32] for better capacity
  dropout: 0.2
  l2_lambda: 0.005  # Reduced from 0.01 for less regularization
  activation:
    name: 'LeakyReLU'
    params:
      negative_slope: 0.1
  final_activation:
    name: 'Sigmoid'  # For proper 0-1 range
    params: {}

# Training constraints
tau:
  min: 0.1
  max: 0.9
  window_size: 5

# Set size constraints
set_size:
  target: 1
  max: 5      # Increased from 3 for more flexibility with 100 classes
  margin: 1.5  # Reduced from 5 to avoid excessive penalties

# Training dynamics
training_dynamics:
  stability_factor: 0.005  # Reduced from 0.02 for less regularization
  separation_factor: 2.0  # Kept the same
  perturbation_noise: 0.01
  permutation_augmentation_prob: 0.5
  coverage_tolerance: 0.02
  coverage_closeness_threshold: 0.01
  coverage_deficit_threshold: 0.02
  size_penalty_boost: 1.5
  coverage_boost: 2.0
  xavier_init_gain: 1.0
  num_workers: 2
  ece_test_points: 10