inherit: base_config.yaml
device: 0
cache:
  enabled: true
  dir: cache
  compression: false
dataset:
  name: imagenet
  num_classes: 1000
  input_size:
  - 224
  - 224
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
model:
  architecture: vit_base_patch16_224
  pretrained_path: models/vit_imagenet.pth
  img_size: 224
  drop_path_rate: 0.1
  drop_rate: 0.1
plot_dir: plots/imagenet
log_dir: logs/imagenet
data_dir: data/imagenet
num_epochs: 100
batch_size: 512
target_coverage: 0.9
training:
  grad_clip:
    enabled: true
    max_norm: 1.0
  loss_weights:
    coverage: 100.0
    size: 1.0
    margin: 0.01
optimizer:
  name: AdamW
  params:
    lr: 0.01
    weight_decay: 0.0
  scheduler:
    name: OneCycleLR
    params:
      max_lr: 0.01
      pct_start: 0.3
      div_factor: 10
      final_div_factor: 100
      anneal_strategy: cos
scoring_function:
  hidden_dims:
  - 32
  - 16
  dropout: 0.1
  l2_lambda: 0.0001
  activation:
    name: LeakyReLU
    params:
      negative_slope: 0.1
  final_activation:
    name: Sigmoid
    params: {}
  batch_norm: false
tau:
  min: 0.001
  max: 0.999
  window_size: 10
set_size:
  target: 1
  max: 10.0
  margin: 10
training_dynamics:
  stability_factor: 0.01
  separation_factor: 0.0
  perturbation_noise: 0.001
  permutation_augmentation_prob: 0.0
  coverage_tolerance: 0.02
  coverage_closeness_threshold: 0.005
  coverage_deficit_threshold: 0.01
  size_penalty_boost: 2.0
  coverage_boost: 5.0
  xavier_init_gain: 0.1
  num_workers: 4
  ece_test_points: 10
cache_on_gpu: true
