# ImageNet specific configuration
inherit: base_config.yaml

# Device configuration
device: 1

dataset:
  name: imagenet
  num_classes: 1000
  input_size: [224, 224]
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  # Dataset splits:
  # - Train: 30,000 samples
  # - Calibration: 10,000 samples
  # - Test: 10,000 samples

model:
  architecture: vit_base_patch16_224
  pretrained_path: models/vit_imagenet.pth
  img_size: 224
  drop_path_rate: 0.1
  drop_rate: 0.1

# Paths
plot_dir: plots/imagenet
log_dir: logs/imagenet
data_dir: data/imagenet

# Training parameters
num_epochs: 50
batch_size: 64
target_coverage: 0.9

# Training configuration
training:
  grad_clip:
    enabled: true
    max_norm: 0.5
  loss_weights:
    coverage: 1.0  # lambda1
    size: 1.0      # lambda2
    margin: 0.2    # margin loss weight

# Optimizer configuration
optimizer:
  name: 'AdamW'
  params:
    lr: 0.001
    weight_decay: 0.01
  scheduler:
    name: 'OneCycleLR'
    params:
      max_lr: 0.001
      pct_start: 0.2
      div_factor: 20
      final_div_factor: 100
      anneal_strategy: 'cos'

# Model architecture
scoring_function:
  hidden_dims: [64, 32]
  dropout: 0.2
  l2_lambda: 0.1
  activation:
    name: 'LeakyReLU'
    params:
      negative_slope: 0.1
  final_activation:
    name: 'Softplus'
    params:
      beta: 10

# Training constraints
tau:
  min: 0.1
  max: 0.9
  window_size: 5

# Set size constraints
set_size:
  target: 1.2
  max: 5.0
  margin: 1 